# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.appinfo import (
    TYPE_CHECKING,
    AppInfo,
    Asset,
    List,
    Optional,
    PartialAppInfo,
    annotations,
    utils,
)

__all__ = ("AppInfo", "PartialAppInfo")
