# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.backoff import (
    Callable,
    ExponentialBackoff,
    Generic,
    Literal,
    T,
    TypeVar,
    Union,
    annotations,
    overload,
    random,
    time,
)

__all__ = ("ExponentialBackoff",)
