# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.colour import (
    CT,
    Any,
    Color,
    Colour,
    Optional,
    Tuple,
    Type,
    TypeVar,
    Union,
    colorsys,
    random,
)

__all__ = ("Colour", "Color")
