# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.file import TYPE_CHECKING, File, Optional, Union, annotations, io, os

__all__ = "File"
