# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.mixins import EqualityComparable, Hashable

__all__ = ("EqualityComparable", "Hashable")
