# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.ext.commands._types import (
    TYPE_CHECKING,
    Any,
    Callable,
    Check,
    Coro,
    CoroFunc,
    Coroutine,
    Error,
    Hook,
    MaybeCoro,
    T,
    TypeVar,
    Union,
    _BaseCommand,
)
