# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.ext.commands.view import (
    ExpectedClosingQuoteError,
    InvalidEndOfQuotedStringError,
    StringView,
    UnexpectedQuoteError,
    _all_quotes,
    _quotes,
)
