# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.types.appinfo import (
    AppInfo,
    BaseAppInfo,
    List,
    Optional,
    PartialAppInfo,
    Snowflake,
    Team,
    TypedDict,
    User,
    _AppInfoOptional,
    _PartialAppInfoOptional,
    annotations,
)
