# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.types.components import (
    ActionRow,
    ButtonComponent,
    ButtonStyle,
    Component,
    ComponentType,
    List,
    Literal,
    PartialEmoji,
    SelectMenu,
    SelectOption,
    TypedDict,
    Union,
    _ButtonComponentOptional,
    _SelectMenuOptional,
    _SelectOptionsOptional,
    annotations,
)
