# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.types.emoji import (
    EditEmoji,
    Emoji,
    Optional,
    PartialEmoji,
    Snowflake,
    SnowflakeList,
    TypedDict,
    User,
)
