# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.types.gateway import Gateway, GatewayBot, SessionStartLimit, TypedDict
