# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.types.role import Role, RoleTags, Snowflake, TypedDict, _RoleOptional, annotations
