# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.types.team import (
    List,
    Optional,
    PartialUser,
    Snowflake,
    Team,
    TeamMember,
    TypedDict,
    annotations,
)
