# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.types.threads import (
    List,
    Literal,
    Optional,
    Snowflake,
    Thread,
    ThreadArchiveDuration,
    ThreadMember,
    ThreadMetadata,
    ThreadPaginationPayload,
    ThreadType,
    TypedDict,
    _ThreadMetadataOptional,
    _ThreadOptional,
    annotations,
)
