# SPDX-License-Identifier: MIT
"""
Aliased moodule. See the same file in the versa folder for more information
Autogenerated by aliasgen.py
"""

from versa.types.user import Literal, Optional, PartialUser, PremiumType, Snowflake, TypedDict, User
